In [61]:
from keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

In [58]:
src_path_training = "geodataset/training/"
src_path_test = "geodataset/test/"
classes = ["canada", "japan", "sweden", "united_states", "france"]

train_datagen = ImageDataGenerator(
    rescale  = 1 / 255.0,
    rotation_range = 20,
    zoom_range = 0.05,
    width_shift_range = 0.05,
    height_shift_range = 0.05,
    shear_range = 0.05,
    horizontal_flip = True,
    fill_mode = "nearest"
)

test_datagen = ImageDataGenerator(rescale = 1 / 255.0)

In [83]:
batch_size = 5
train_generator = train_datagen.flow_from_directory(
    directory=src_path_training,
    target_size=(224, 224),
    color_mode="rgb",
    batch_size=batch_size,
    class_mode="categorical",
    subset="training",
    shuffle=True,
    seed=42
)
valid_generator = train_datagen.flow_from_directory(
    directory=src_path_training,
    target_size=(224, 224),
    color_mode="rgb",
    batch_size=batch_size,
    class_mode="categorical",
    subset="validation",
    shuffle=False,
    seed=42
)
test_generator = test_datagen.flow_from_directory(
    directory=src_path_test,
    target_size=(224, 224),
    color_mode="rgb",
    batch_size=1,
    class_mode=None,
    shuffle=False,
    seed=42
)

Found 50 images belonging to 5 classes.
Found 0 images belonging to 5 classes.
Found 23 images belonging to 1 classes.


In [84]:
def prepare_model():
    model = Sequential()
    model.add(Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(224, 224, 3)))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Flatten())
    model.add(Dense(12, activation='relu'))
    model.add(Dense(5, activation='sigmoid'))
    model.compile(loss="binary_crossentropy", optimizer="adam", metrics=['accuracy'])
    return model

In [85]:
model = prepare_model()
model.fit(train_generator, 
                    validation_data=train_generator, 
                    steps_per_epoch=train_generator.n//train_generator.batch_size,
                    validation_steps = valid_generator.n//valid_generator.batch_size,
                    epochs=5)

Epoch 1/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 118ms/step - accuracy: 0.1194 - loss: 4.4971 - val_accuracy: 0.2000 - val_loss: 1.7664
Epoch 2/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.2000 - val_loss: 1.7633
Epoch 3/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 93ms/step - accuracy: 0.1736 - loss: 1.0250 - val_accuracy: 0.2000 - val_loss: 0.6907
Epoch 4/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 0.0000e+00 - val_accuracy: 0.2000 - val_loss: 0.6907
Epoch 5/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 90ms/step - accuracy: 0.2017 - loss: 0.6902 - val_accuracy: 0.2000 - val_loss: 0.6888


In [86]:
predict = model.predict(test_generator)
y_classes = predict.argmax(axis=-1)
print(predict)
print(y_classes)
print(classes[np.argmax(predict)])
files = test_generator.filenames
for i, p in enumerate(predict):
    index=np.argmax(p)
    classname = classes[index]
    prob = p[index]
    print("for file ", files[i], ' predicted class is ', classname, ' with probability ', prob)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296   0.49670497 0.49802977]
 [0.49533385 0.49420327 0.497296 